= Entity Polymorphism

In certain cases it is beneficial to have a polymorphic hierarchy in entity structure.
Subtypes in polymorphic entity hierarchy inherit `@CommandHandler`s, `@EventSourcingHandler`s
and `@CommandHandlerInterceptor`s from the parent entities.
Based on the entity identifier the correct entity type is loaded and command is executed on it.
Let's take a look at the following example:

[source,java]
----
public abstract class Card {}

public class GiftCard extends Card {}

public class ClosedLoopGiftCard extends GiftCard {}

public class OpenLoopGiftCard extends GiftCard {}

public class RechargeableGiftCard extends ClosedLoopGiftCard {}

----

We can define this structure as Polymorphic Entity of type `GiftCard` and subtypes of `ClosedLoopGiftCard`,
`OpenLoopGiftCard`, and `RechargeableGiftCard`.
If there are handlers present on `Card` class, those will be present on all entities as well.

While modeling a polymorphic entity hierarchy it is important to keep these constraints in mind:

* It is not allowed to have a static `@CommandHandler` (creational command handler) on an abstract entity.
The rationale for this is that an abstract entity can never be created.

* Having creational command handlers of the same command name on different entities in the same hierarchy is forbidden too, since Axon cannot derive which one to invoke.

* In a polymorphic entity hierarchy it is not allowed to have multiple entity identifier fields.

== Registering entity subtypes

A polymorphic entity hierarchy can be registered via the configuration API.
When using event sourcing, use `EventSourcingConfigurer` to register the entity hierarchy.

Do note that children of the parent entity that you do not register as a subtype will be *automatically*
registered by the framework as a subtype.
So, in the following example, the `ClosedLoopGiftCard` is transitively registered as a subtype of `GiftCard`.
However, if there is a `LimitedRechargeableGiftCard extends RechargeableGiftCard` defined, the framework will not pick it up *automatically* since it is not a direct child of the parent entity.

[source,java]
----
import org.axonframework.eventsourcing.configuration.EventSourcingConfigurer;
import org.axonframework.messaging.core.configuration.MessagingConfigurer;

public class AxonConfig {
    // omitting other configuration methods...
    public EventSourcingConfigurer giftCardConfigurer(MessagingConfigurer configurer) {
        Set<Class<? extends GiftCard>> subtypes = new HashSet<>();
        subtypes.add(OpenLoopGiftCard.class);
        subtypes.add(RechargeableGiftCard.class);

        return EventSourcingConfigurer.create(configurer)
                                      .configureAggregate(GiftCard.class)
                                      .withSubtypes(subtypes);
    }

    // ...
}

class GiftCard {
    // omitted implementation for brevity
}

class OpenLoopGiftCard extends GiftCard {
    // omitted implementation for brevity
}

class RechargeableGiftCard extends GiftCard {
    // omitted implementation for brevity
}
----

[TIP]
.Polymorphic Entities in Spring
====
If you are using Spring, Axon will automatically detect polymorphic entities based on the `@Aggregate` annotations and class hierarchy.
The `@Aggregate` annotation needs to be put on the shared parent class that contains the entity identifier, as well as every subclass that is a potential instance type of that shared parent class.
====