= Known Issues and Workarounds
:navtitle: Known Issues and Workarounds

As with tool, library, or framework, there are well-known issues you might potentially come up against.
Especially given the fact Axon Framework will integrate with a wide variety of other tools, it becomes rough to deal with everything.

This page intends to provide the biggest "gotchas," with optional workarounds, which you can see below.

[NOTE]
.Where is issue XYZ?
====
This page can by no means contain **all** possible issues out there.
But, that does not mean we are not open for suggestions.

This documentation, just as the framework, is open source as well.
Hence, if you have found something problematic that you think should be added to the list, be sure to file an issue and (ideally!) a pull request.

You can make an enhancement request by clicking link:https://github.com/AxonFramework/AxonFramework/issues/new?assignees=&labels=Type%3A+Enhancement&projects=&template=2_enhancement_request.md[here].
When looking to provide a pull request, be sure to adjust link:https://github.com/AxonFramework/AxonFramework/blob/master/docs/old-reference-guide/modules/ROOT/pages/serialization.adochttps://github.com/AxonFramework/AxonFramework/blob/master/docs/old-reference-guide/modules/ROOT/pages/known-issues-and-workarounds.adoc[this file].
====

== RDBMS Storage and LOB columns

When storing the serialized formats of, for example, xref:axon-framework-reference:events:event-processors/streaming.adoc#tracking-tokens[tokens], xref:axon-framework-reference:sagas:index.adoc[sagas], xref:axon-framework-reference:tuning:event-snapshots.adoc[snapshots], or xref:axon-framework-reference:events:infrastructure.adoc[events], it is good to know Axon uses the (B)LOB for these columns in your RDBMS of choice.
Some databases react unexpectedly to this, with a clear case being link:https://www.postgresql.org/[PostgreSQL].
It uses a mechanism it calls link:https://wiki.postgresql.org/wiki/TOAST["TOAST"] to move data that's too large to another table.
Especially (B/C)LOB columns are automatically replaced for the OID type.
Hence, all your tokens, sagas, snapshots, and events will automatically move to another table, with all added overhead coming with it.
Using xref:axon-server-reference::index.adoc[Axon Server] will, obviously, resolve this for your events and snapshots, as you would no longer use an RDBMS in that case.
But even when using Axon Server, the predicament remains for tokens and sagas.
For those cases, it would be wise to replace the TOAST behavior entirely.
The most straightforward way, is to enforce the use of the `bytea` column type; with some additional steps, of course.
The following link:https://www.axoniq.io/blog/axonframework-and-postgresql-without-toast[blog post] explains it in great detail, so be sure to check it out.


[NOTE]
.Where is issue XYZ?
====
This page can by no means contain **all** possible issues out there.
But, that does not mean we are not open for suggestions.

This documentation, just as the framework, is open source as well.
Hence, if you have found something problematic that you think should be added to the list, be sure to file an issue and (ideally!) a pull request.

You can make an enhancement request by clicking link:https://github.com/AxonFramework/AxonFramework/issues/new?assignees=&labels=Type%3A+Enhancement&projects=&template=2_enhancement_request.md[here].
When looking to provide a pull request, be sure to adjust link:https://github.com/AxonFramework/AxonFramework/blob/master/docs/old-reference-guide/modules/ROOT/pages/serialization.adochttps://github.com/AxonFramework/AxonFramework/blob/master/docs/old-reference-guide/modules/ROOT/pages/known-issues-and-workarounds.adoc[this file].
====
