/*
 * Copyright (c) 2010-2026. Axon Framework
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.axonframework.test.fixture;

import org.axonframework.common.configuration.AxonConfiguration;
import org.axonframework.messaging.commandhandling.CommandBus;
import org.axonframework.messaging.core.MessageTypeResolver;
import org.axonframework.messaging.core.unitofwork.UnitOfWorkFactory;
import org.axonframework.messaging.eventhandling.EventSink;
import org.axonframework.test.FixtureExecutionException;

import java.util.Objects;

/**
 * Per-test context that holds the resolved fixture components. Created once per logical test (via
 * {@link AxonTestFixture#with(org.axonframework.common.configuration.ApplicationConfigurer) AxonTestFixture.with()})
 * and reused across the fixture phase chain (Given → When → Then → {@code and()}).
 * <p>
 * This ensures that per-test state — such as the test isolation identifier generated by
 * {@link TestIsolationEnhancer} — remains stable across {@code and()} chains. Without this, each
 * {@code new AxonTestFixture(configuration, customization)} call in {@code and()} would re-invoke the
 * {@link FixtureCustomizer}, generating a new test identifier and breaking event visibility across phases.
 *
 * @author Theo Emanuelsson
 * @since 5.1.0
 */
class TestContext {

    private final AxonConfiguration configuration;
    private final AxonTestFixture.Customization customization;
    private final CommandBus commandBus;
    private final EventSink eventSink;
    private final RecordingComponentsRegistry recordings;
    private final MessageTypeResolver messageTypeResolver;
    private final UnitOfWorkFactory unitOfWorkFactory;

    private TestContext(
            AxonConfiguration configuration,
            AxonTestFixture.Customization customization,
            CommandBus commandBus,
            EventSink eventSink,
            RecordingComponentsRegistry recordings,
            MessageTypeResolver messageTypeResolver,
            UnitOfWorkFactory unitOfWorkFactory
    ) {
        this.configuration = configuration;
        this.customization = customization;
        this.commandBus = commandBus;
        this.eventSink = eventSink;
        this.recordings = recordings;
        this.messageTypeResolver = messageTypeResolver;
        this.unitOfWorkFactory = unitOfWorkFactory;
    }

    /**
     * Creates a new {@code TestContext} by resolving all components from the given configuration and applying
     * any registered {@link FixtureCustomizer}.
     *
     * @param configuration The configuration to resolve components from.
     * @param customization The fixture customization settings.
     * @return A new {@code TestContext} holding the resolved and customized components.
     */
    static TestContext create(AxonConfiguration configuration, AxonTestFixture.Customization customization) {
        Objects.requireNonNull(configuration, "Configuration may not be null.");
        Objects.requireNonNull(customization, "Customization may not be null.");

        var commandBus = configuration.getComponent(CommandBus.class);
        var eventSink = configuration.getComponent(EventSink.class);
        var recordings = configuration.getOptionalComponent(RecordingComponentsRegistry.class)
                .orElseThrow(() -> new FixtureExecutionException(
                        "RecordingComponentsRegistry not found in Configuration. "
                                + "Ensure MessagesRecordingConfigurationEnhancer is registered."
                ));
        Objects.requireNonNull(recordings.commandBus(),
                "RecordingCommandBus is not available. "
                        + "Ensure CommandBus is resolved before constructing AxonTestFixture.");
        Objects.requireNonNull(recordings.eventSink(),
                "RecordingEventSink is not available. "
                        + "Ensure EventSink is resolved before constructing AxonTestFixture.");

        var components = configuration.getOptionalComponent(FixtureCustomizer.class)
                .map(c -> c.customize(new FixtureConfiguration(commandBus, eventSink, recordings)))
                .orElse(new FixtureConfiguration(commandBus, eventSink, recordings));

        return new TestContext(
                configuration,
                customization,
                components.commandBus(),
                components.eventSink(),
                components.recordings(),
                configuration.getComponent(MessageTypeResolver.class),
                configuration.getComponent(UnitOfWorkFactory.class)
        );
    }

    AxonConfiguration configuration() {
        return configuration;
    }

    AxonTestFixture.Customization customization() {
        return customization;
    }

    CommandBus commandBus() {
        return commandBus;
    }

    EventSink eventSink() {
        return eventSink;
    }

    RecordingComponentsRegistry recordings() {
        return recordings;
    }

    MessageTypeResolver messageTypeResolver() {
        return messageTypeResolver;
    }

    UnitOfWorkFactory unitOfWorkFactory() {
        return unitOfWorkFactory;
    }
}
