services:
  axonserver:
    image: "docker.axoniq.io/axoniq/axonserver"
    hostname: axonserver
    ports:
      - 8024
      - 8124
    environment:
      AXONIQ_AXONSERVER_STANDALONE: true
      AXONIQ_AXONSERVER_DEVMODE_ENABLED: true
