= Queries

The third and final type of "Messages" that an Axon application is associated with are _*Query Messages (or simply Queries).*_ This section of the reference guide intends to cover in detail the capabilities that the Axon Framework provides to help facilitate Query Message Development.

A summary of the various sub-sections is given below.

[cols="<,<"]
|===
|Sub-Section |Purpose 

|xref:query-processing.adoc[Query Processing] |Short introduction to the Query Processing capabilities provided by the Axon Framework
|xref:query-dispatchers.adoc[Query Dispatchers] / xref:query-handlers.adoc[Query Handlers] |Functional Development concerns for Query Messages using the Axon Framework
|xref:implementations.adoc[Implementations] |Non-Functional Development concerns for Query Messages using the Axon Framework
|xref:configuration.adoc[Configuration] |Configuration concerns for Query Messages using the Axon Framework
|===

This guide is complemented by a video tutorial which gives a practical demonstration of the concepts explained in this section. The tutorial is available at -&gt; link:https://www.youtube.com/watch?v=jS1vfc5EohM&feature=youtu.be[Axon Coding Tutorial - Query Messages]