spring:
  docker:
    compose:
      file: file:examples/docker-compose.yaml
      lifecycle-management: start_only
  datasource:
    url: jdbc:h2:mem:university;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  main:
    web-application-type: reactive
axon:
  converter:
    general: jackson
  server:
    enabled: true

springdoc:
  swagger-ui:
    try-it-out-enabled: true
