:navtitle: Feature: Create Course
:reftext: Implementing the create new course feature

= Create course feature

When you implement a new feature the first step is to define the messages which will be the input and output of it.
In Axon Framework messages are the first-class citizen and everything is designed around them.
While designing the app and also during execution - you're always in the context of some command.

Let's focus on the first feature for this sample app.
We need to be able to create a new course.
Could you imagine a faculty without any courses, which students may subscribe to?
I can't either!

== Define messages

Messages are the contract between different parts of our system, so you need to pay attention to craft them correctly.
Event Modeling helps a lot, thanks to it completeness check you can be sure you don't forgot about anything.
So let's take the first Write Slice on the table.
We can name it shortly as `CreateCourse`->`CourseCreated`.
Now we're going to translate the sticky notes to the code.
The orange sticky is an event, and every event needs a cause, which is a command which may trigger the event.
In this case it's a `CreatCourse` on the blue sticky note.

In Axon Framework 5, we typically define commands and events as simple data structures - using Java `records`.
You can also use Java classes if you really want, but records fulfill nicely the characteristic of messages, because they are immutable by definition.
As you remember we follow the Vertical Slice Architecture so please create files with corresponding content:

* `CreateCourse` in the `io.axoniq.demo.university.faculty.write.createcourse` package (we place command inside the slice package, because the command has only one handler)
* `CourseCreated` in the `io.axoniq.demo.university.faculty.events` package (events are shared between slices, there may be 0 to many handlers for the same event)

[source,java]
.src/main/java/io/axoniq/demo/university/faculty/write/createcourse/CreateCourse.java
----
package io.axoniq.demo.university.faculty.write.createcourse;

import io.axoniq.demo.university.faculty.write.CourseId;
import org.axonframework.modelling.command.annotation.TargetEntityId;

public record CreateCourse(
    CourseId courseId,
    String name,
    int capacity
) {}
----

[NOTE]
====
You may notice that for the `courseId` field we use `CourseId` value object.
It's not necessary, but it's a convention.
This class provides type safety and domain semantics for course identifiers.
Thanks to that you won't mix CourseId with other identifiers in the system like StudentId.
The class may be as simple as `public record CourseId(String raw) {}`.
In the sample we have also some additional helpful methods which you may find in the repository, but for now this is enough.
====

[source,java]
.src/main/java/io/axoniq/demo/university/faculty/events/CourseCreated.java
----
package io.axoniq.demo.university.faculty.events;

import io.axoniq.demo.university.faculty.FacultyTags;
import org.axonframework.eventsourcing.annotations.EventTag;

public record CourseCreated(
    @EventTag String courseId, // <1>
    String name,
    int capacity
) {}
----

<1> The `courseId` is annotated with `@EventTag`, which allows Axon to tag the event as connected with the 'Course' business entity and then use it for efficiently retrieval of the events related to given 'Course'.
It's a simple String - for events we prefer to avoid Value Objects, because events need to be deserialized regardless of the current rules for Value Objects creations.

== Specification by example

We already have our first slice API defined.
Now we're going to specify the slice behaviour.
For that purpose we're going to follow Test-First approach and write test in Given-When-Then convention, perfectly supported by Axon Test Fixture.
Still, everything is around messages.
So keep focus on the current command - `CreateCourse` and create corresponding `CreateCourseTest` class in the `io.axoniq.demo.university.faculty.write.createcourse` package.

TIP: You can also use your IDE to create the unit test class.
Open the `CreateCourse` class and ask your IDE to generate the corresponding unit test.
Depending on your IDE, the shortcut or menu may vary, but it's a shortcut worth knowing for your IDE.

[source,java]
.src/test/java/io/axoniq/demo/university/faculty/write/createcourse/CreateCourse.java
----
package io.axoniq.demo.university.faculty.write.createcourse;

class CreateCourseTest {

}
----

=== Defining the Test Fixture

Axon Framework test fixture allows you to execute certain test cases against provided configuration.
It may be your module/component or event whole application.
Do you remember the configurer which we used while bootstrapping the application?
Now it's time to use it in order to initialize our TestFixture.
We need to have access to application components in tests to verify their behaviour.

[source,java]
.src/test/java/io/axoniq/demo/university/faculty/write/createcourse/CreateCourse.java
----
package io.axoniq.demo.university.faculty.write.createcourse;

class CreateCourseTest {

    private AxonTestFixture fixture;

    @BeforeEach // <1>
    void beforeEach() {
        fixture = AxonTestFixture.with(UniversityAxonApplication.configurer()); // <2>
    }

}
----

<.> The `@BeforeEach` marks this method to be called before any test is executed in our test class.
Adding the code to create the `AxonTestFixture` here will ensure that we have a fresh fixture for each test case, and thus we make our different tests independent.
<.> This line creates a new `AxonTestFixture` based on our configuration.

=== Testing the command

Thanks to the help of the `AxonTestFixture` we can now create a test with the following structure:

- *Given*: Set the initial state for our test.
Since we are designing our system to follow Event-Sourcing patterns, we need to set the list of events that have already happened before receiving the command.
- *When*: Specify the command whose execution we want to test.
In this case, we will test the processing of a `CreateCourse`.
- *Expect*: We can instruct the fixture on the expectations we have from our system after processing the command.
In an Event-Sourcing system, we will specify these expectations in the form of what events should have been produced by the command handler as a result of processing the command.

So, let's define a method in our unit test to check that our system can successfully process the request to create a course:

[source,java]
.src/test/java/io/axoniq/demo/university/faculty/write/createcourse/CreateCourse.java
----
package io.axoniq.demo.university.faculty.write.createcourse;

import java.util.UUID;class CreateCourseTest {

    private AxonTestFixture fixture;

    @BeforeEach // <1>
    void beforeEach() {
        fixture = AxonTestFixture.with(UniversityAxonApplication.configurer()); // <2>
    }

    @Test
    void givenNotExistingCourse_WhenCreateCourse_ThenSuccess() {
        var courseId = new CourseId(UUID.randomUUID().toString());
        var courseName = "Event Sourcing in Practice";
        var capacity = 3;

        fixture.given() // <1>
               .noPriorActivity()
               .when()
               .command(new CreateCourse(courseId, courseName, capacity)) // <2>
               .then()
               .events(new CourseCreated(courseId.raw(), courseName, capacity)); // <3>
    }

}
----

<.> In our case, when we receive the `CreateCourse` command, we expect that no previous events were received in the system.
We may even skip the whole `given` section if there is nothing to execute.
<.> We provide the `CreateCourse` command we want to dispatch against the system (scoped to the given configuration).
<.> After successfully processing the `CreateCourse`, we expect the publication of a new `CourseCreated` event with the details of the new course.

When we execute the test you will see in the stack trac a following error:

[,console]
----
org.axonframework.commandhandling.NoHandlerForCommandException: No handler was subscribed for command [io.axoniq.demo.university.faculty.write.createcourse.CreateCourse#0.0.1].
----

It means that we need to implement the handler for the `CreateCourse` command.
And this will be our next step!

=== Implementing the Command Handler

To process a `CreateCourse` command in our application, we must define a method that receives the command as an argument.
To indicate that the method should be invoked upon receiving a command, we will add the `@CommandHandler` annotation provided by AxonFramework.
Let's create a new class for that inside the slice package and name it `CreateCourseCommandHandler` and implement the minimum required to make the test pass.

[source,java]
.src/main/java/io/axoniq/demo/university/faculty/write/createcourse/CreateCourseCommandHandler.java
----
package io.axoniq.demo.university.faculty.write.createcourse;

import org.axonframework.commandhandling.annotation.CommandHandler;
import org.axonframework.eventhandling.EventSink;
import org.axonframework.messaging.unitofwork.ProcessingContext;
import org.axonframework.modelling.command.annotation.InjectEntity;

class CreateCourseCommandHandler {

    @CommandHandler // <1>
    public void handle(
            CreateCourse command,  // <2>
            EventSink eventSink,  // <3>
            ProcessingContext processingContext  // <4>
    ) {
        var event = new CourseCreated(command.courseId().raw(), command.name(), command.capacity());  // <5>
        var message = toMessage(event); // <6>
        eventSink.publish(processingContext, message); // <7>
    }

    private static EventMessage<?> toMessage(Object payload) {
        return new GenericEventMessage<>(
                new MessageType(payload.getClass()),
                payload
        );
    }

}
----

<.> The `org.axonframework.commandhandling.annotation.CommandHandler` annotation instructs Axon Framework to call this method upon receiving commands.
<.> The type of the argument indicates to Axon Framework which type of commands should be linked to the invocation of this method.
<.> The `EventSink` is a component that allows us to publish the Event that notifies the change in the state of our system.
In this case, to notify that the *course has been created*.
<.> The `ProcessingContext` is a component that allows us to manage the lifecycle of the message processing.
Allows us to publish events in the context of the current command so the events will be published after successful command execution.
<.> The `EventSink` interface require implementation of the `EventMessage` as a second argument so we provide one.
<.> The invocation of `EventSink#publish` stage event to be published after the current `ProcessingContext` is completed.

Have you already tried to run the test?
Unfortunately it will fail again.
What we need to do now, we need to register the `CreateCourseCommandHandler` in the Axon Framework configuration.
We're going to do it in dedicated class `CreateCourseConfiguration` which will be responsible for spinning up the infrastructure for the whole slice.

[source,java]
.src/main/java/io/axoniq/demo/university/faculty/write/createcourse/CreateCourseConfiguration.java
----
package io.axoniq.demo.university.faculty.write.createcourse;

public class CreateCourseConfiguration {

    public static EventSourcingConfigurer configure(EventSourcingConfigurer configurer) {
        var commandHandlingModule = StatefulCommandHandlingModule.named("CreateCourse") // <1>
                .commandHandlers()
                .annotatedCommandHandlingComponent(c -> new CreateCourseCommandHandler()); // <2>
        return configurer.registerStatefulCommandHandlingModule(commandHandlingModule); // <3>
    }

}
----

<.> The `StatefulCommandHandlingModule` is a component that allows us to register the command handler for the `CreateCourse` command.
For our current needs we skip `entities` configuration, because we don't need the state yet.
<.> The `annotatedCommandHandlingComponent` method allows us to register the `CreateCourseCommandHandler` as the command handler for the `CreateCourse` command.
<.> The `registerStatefulCommandHandlingModule` method registers the command handler module in the Axon Framework configuration.

When the slice configurer is ready we can register it to the main application configurer.
To do that let's introduce changes in our main `UniversityAxonApplication` class.

[source,java]
./src/main/java/io/axoniq/demo/university/UniversityAxonApplication.java
----
public class UniversityAxonApplication {

    public static ApplicationConfigurer<?> configurer() {
        var configurer = EventSourcingConfigurer.create();
        configurer = CreateCourseConfiguration.configure(configurer);
        return configurer;
    }

}
----

Let's check our test again, now everything is green!
Can we say that the work is done?
Not yet!
Because we have some business rules defined in the Given-When-Then specifications.
The course cannot be created if it already exists.
So let's add a test case for that to the `CreateCourseTest` class as below

[source,java]
.src/test/java/io/axoniq/demo/university/faculty/write/createcourse/CreateCourse.java
----
package io.axoniq.demo.university.faculty.write.createcourse;

import java.util.UUID;

class CreateCourseTest {

    // fixture creation skipped for brevity

    @Test
    void givenCourseCreated_WhenCreateCourse_ThenSuccess_NoEvents() {
        var courseId = new CourseId(UUID.randomUUID().toString());
        var courseName = "Event Sourcing in Practice";
        var capacity = 3;

        fixture.given()
               .event(new CourseCreated(courseId.raw(), courseName, capacity)) // <1>
               .when()
               .command(new CreateCourse(courseId, courseName, capacity)) // <2>
               .then()
               .success() // <3>
               .noEvents(); // <3>
    }

}
----

<1> In our case, when we receive the `CreateCourse` command, we expect that `CourseCreated` event happened in the past, so the Course already exists in the system.
<2> We provide the `CreateCourse` command we want to dispatch against the system (scoped to the given configuration), so will be handled by registered handler.
<3> After successfully processing the `CreateCourse`, we expect the command handler executed successfully, but no events were published.

If you ran this test you may notice that it fails, because of unexpected event was published!

[,console]
----
org.axonframework.test.AxonAssertionError: The published events do not match the expected events

Expected  |  Actual
----------|----------
         <|> io.axoniq.demo.university.faculty.events.CourseCreated
----

Do you remember that we haven't used any state inside the *Stateful* command handling component?
Now we definitiely do that, because the system decision what to do with the command will be based on the state derived from the historial events.

=== Validate the Command against the state

The only think we need to know about certain course for the `CreateCourse` command handling if it already exists or not.
So let's add the `State` class which will be responsible for providing that information.
I will use the term `State`, because it's not everything what we know about the `Course`, we don't need subscribed students etc. just for this command purposes.
But you can name it `Course` as well, but keep in mind it's just a part of information needed for the validation of this command.
I'm going to put it as internal class in the handler, because it will be used just there.

[source,java]
.src/main/java/io/axoniq/demo/university/faculty/write/createcourse/CreateCourseCommandHandler.java
----
package io.axoniq.demo.university.faculty.write.createcourse;

class CreateCourseCommandHandler {

    @EventSourcedEntity(tagKey = "courseId") // <1>
    public static class State {

        private boolean created = false; // <2>

        @EventSourcingHandler // <3>
        public void apply(CourseCreated event) {
            this.created = true;
        }
    }

    @CommandHandler
    public void handle(
            CreateCourse command,
            @InjectEntity(idProperty = "courseId") State state, // <4>
            EventSink eventSink,
            ProcessingContext processingContext
    ) {
        if(state.created) { // <5>
            return;
        }
        var event = new CourseCreated(command.courseId().raw(), command.name(), command.capacity());
        eventSink.publish(processingContext, toMessage(event));
    }

}

----

<1> The `@EventSourcedEntity` annotation indicates that this class state is derived from the events published with the given tag key (`courseId` in this case).
We've already annotation `courseId` property in the `CourseCreated` event class with `@EventTag`, so the event will be applied while loading the entity.
<2> The properties needed to guard certain business rules.
In this case we need to know if the course was already created or not.
While executing the command we don't care about the name or other properties.
<3> The `@EventSourcingHandler` annotation indicates to Axon Framework to link this method to the reception of an event.
It will be called while the entity is being loaded.
Axon Framework will use the type of the annotated method argument to link this method to the specific type of event.
<4> The `@InjectEntity` annotation indicates to Axon Framework to inject the entity with the given identifier property which needs to be present in the processed command.
In this case, we want to inject the `State` entity with the `courseId` property.
<5> The `if` statement checks if the course was already created.
If it was, we don't need to do anything, so we just return from the method.

NOTE: The `EventSourcingHandler` will be called right after the event publication by the `CommandHandler`.
But it also will be invoked in the future, for the same event, when the system receives another command for the same `bikeId` (identified because the command has the same  `@AggregateIdentifier`) and Axon Framework needs to regenerate the current state of the `Bike` instance, by replaying all previous events with the same `bikeId`.

CAUTION: In the `EventSourcingHandler` method, we should never validate or ignore the changes represented by the event received.
The reception of the event and the invocation of the method imply that the command has already been processed previously.
So we can't ignore or reject those changes *because they already happened*

As before, the last step to fulfill the next test case are changes in our configuration.
Come back to the `CreateCourseConfiguration` class and add the `State` class to the configuration.

[source,java]
.src/main/java/io/axoniq/demo/university/faculty/write/createcourse/CreateCourseConfiguration.java
----
package io.axoniq.demo.university.faculty.write.createcourse;

public class CreateCourseConfiguration {

    public static EventSourcingConfigurer configure(EventSourcingConfigurer configurer) {
        var stateEntity = EventSourcedEntityBuilder
                .annotatedEntity(CourseId.class, CreateCourseCommandHandler.State.class);  // <1>

        var commandHandlingModule = StatefulCommandHandlingModule.named("CreateCourse")
                .entities()
                .entity(stateEntity)  // <2>
                .commandHandlers()
                .annotatedCommandHandlingComponent(c -> new CreateCourseCommandHandler());
        return configurer.registerStatefulCommandHandlingModule(commandHandlingModule);
    }

}
----

<1> The `EventSourcedEntityBuilder` is a builder that allows us to create an entity with the given identifier type and state class.
<2> The `entity` method allows us to register the `State` class as the entity for the `CreateCourse` command handling module.

With this step, we have completed the code to process a Command that represents the request to register a new bike in our system.
You may run the tests again and see that all of them should pass!

== First in, first out.

Do you like green tests?
Me too!
But what I like even more are green slices on Event Modeling.
So if you use this approach now you can mark your first slice as implemented!
Congratulations!
No let's move to more complex examples or read about alternative approach - how you can do the same without annotations.