:navtitle: Introduction
:reftext: Building an Axon Framework 5 Application from Scratch

= Introduction

Building a new application from scratch can be daunting, especially when learning something new.
This tutorial will guide you through the various stages of development, starting with creating your first project and explaining the capabilities of Axon Framework 5.
The Axon Framework 5 introduces a lot of changes, so even if you are already familiar with Axon Framework 4, we still recommend you to go through this tutorial.

The result of the guide is a simple application, where you can play around with the concepts of Axon Framework 5.
It's not production ready yet, because the Axon Framework 5 hasn't been released, it's in the milestone phase.

This tutorial will guide you through the creation of a "University Registrations Application" using Axon Framework 5.
You can follow the steps in the tutorial to complete the project from scratch or check out our link:https://github.com/AxonIQ/university-demo/[University Demo repository in GitHub,role=external,window=_blank].

== Your opinion matters!

Keep in mind it's a milestone version, so it may be a subject to change.
Because of that your opinion is even more valuable to us, you may shape to future of your favorite Event Sourcing tool together with us!
After playing around with that please share your feedback here: FORM LINK.
You can always reach out our team directly on LinkedIn, we will be so happy to talk with you.