:navtitle: Introduction and the Sample Domain
:reftext: Building an Axon Framework 5 Application from Scratch

= Introduction

Building a new application from scratch can be daunting, especially when learning something new.
This tutorial will guide you through the various stages of development, starting with creating your first project and explaining the capabilities of Axon Framework 5.

The result is a simple application, where you can play around with the concepts of Axon Framework 5.
It's not production ready yet, because the Axon Framework 5 hasn't been released, it's in the milestone phase.

This tutorial will guide you through the creation of a "University Registrations Application" using Axon Framework 5.
You can follow the steps in the tutorial to complete the project from scratch or check out our University Demo repository in GitHub.

== Your opinion matters!

Keep in mind it's a milestone version, so it may be a subject to change.
Because of that your opinion is even more valuable to us, you may shape to future of your favorite Event Sourcing tool together with us!
After playing around with that please share your feedback here: FORM LINK.
You can always reach out our team directly on LinkedIn, we will be so happy to talk with you.

== The sample domain (University - Faculty)

In this sample, we are dealing with the University Domain.
The initial examples will be around the Faculty Bounded Context.

In the context there are students and courses, that students can subscribe to.
A student can enroll in the faculty.
The faculty can decide to create a course with assigned capacity—the number of students who can subscribe to a course.
The capacity of the course must be maintained.
After the course has been created, its capacity can be changed.
A student can subscribe to a course and unsubscribe.

== Event Modeling

TODO: Miro board Screen!!!

After an Event Modeling (which you can see above) session we have identified following events:
* `StudentEnrolledFaculty` - a fact that a student has enrolled faculty * `CourseCreated` - a fact that a course has been created with assigned capacity * `CourseCapacityChanged` - a fact that the capacity of the course has changed * `StudentSubscribed` - a fact that the student has subscribed to the course * `StudentUnsubscribed` - a fact that the student has unsubscribed from the course

We will model only commands for Subscribing to/Unsubscribing from a course for the sample's simplicity.

