:navtitle: Building an Axon Framework 5 Application from Scratch
= Building an Axon Framework 5 Application from Scratch

Building a new application from scratch can be daunting, especially when learning something new.
This tutorial will guide you through the various stages of development, starting with creating your first project and explaining the capabilities of Axon Framework 5.

The result is a simple application you can deploy in "production".
The tutorial then shows you how to evolve the application, make changes, and deploy it in different scenarios.

This tutorial will guide you through the creation of a "University Registrations Application" using Axon Framework 5 and Axon Server.
You can follow the steps in the tutorial to complete the project from scratch or check out our University Demo repository in GitHub.

== Your opinion matters!

Keep in mind it's a milestone version, so it may be a subject to change.
Because of that your opinion is even more valuable to us, you may shape to future of your favorite Event Sourcing tool together with us!
After playing around with that please share your feedback here: FORM LINK.
You can always reach out our team directly on LinkedIn, we will be so happy to talk with you.