:navtitle: Vertical Slice Architecture
:reftext: Creating A New Axon Framework Project

= Create new Axon Framework project with maven

Let's use Maven and/or your favorite IDE and just create a Maven project.
You may also use Gradle as well, but this tutorial will be focused on Maven.
Please keep in mind Axon Framework 5 requires Java 21 or higher.

[NOTE]
====
After the creation please make sure to set the following project properties.

[horizontal]
groupId:: io.axoniq.demo.university
artifactId:: university-demo
version:: 1.0.0-SNAPSHOT
====

== Axon Framework dependencies

In this step we will configure the dependencies to use Axon Framework 5 in our project.
To enable the use of Axon Framework, we can configure the required Axon Framework dependencies in our project's `pom.xml` file.
Nevertheless, depending on the specific features we plan to use later, we may need to add additional dependencies for other libraries or tools later (for example, `micrometer` or `reactor`).

Below you may see the resulting pom.
Please ensure you have the following properties and dependencies in your `pom.xml` file:

[source,xml]
./pom.xml
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.axoniq.demo.university</groupId>
    <artifactId>university-demo</artifactId>
    <version>1.0.0-SNAPSHOT</version>

    <properties>
        <assertj.version>3.27.3</assertj.version>
        <axon.version>5.0.0-SNAPSHOT</axon.version>
        <hamcrest.version>3.0</hamcrest.version>
        <junit.version>5.12.1</junit.version>
        <log4j.version>2.24.3</log4j.version>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <java.version>21</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven-surefire-plugin.version>3.2.5</maven-surefire-plugin.version>
    </properties>

    <dependencies>
        <!-- Axon Framework Dependencies -->
        <dependency>
            <groupId>org.axonframework</groupId>
            <artifactId>axon-messaging</artifactId>
            <version>${axon.version}</version>
        </dependency>
        <dependency>
            <groupId>org.axonframework</groupId>
            <artifactId>axon-modelling</artifactId>
            <version>${axon.version}</version>
        </dependency>
        <dependency>
            <groupId>org.axonframework</groupId>
            <artifactId>axon-eventsourcing</artifactId>
            <version>${axon.version}</version>
        </dependency>
        <dependency>
            <groupId>org.axonframework</groupId>
            <artifactId>axon-configuration</artifactId>
            <version>${axon.version}</version>
        </dependency>

        <!-- Log4j Dependencies -->
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>${log4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>${log4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j2-impl</artifactId>
            <version>${log4j.version}</version>
        </dependency>

        <!-- Test Dependencies -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>${assertj.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest</artifactId>
            <version>${hamcrest.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.axonframework</groupId>
            <artifactId>axon-test</artifactId>
            <version>${axon.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven-surefire-plugin.version}</version>
            </plugin>
        </plugins>
    </build>
</project>
----

== Project structure

We will design our project follows a *Vertical Slice Architecture* approach, which organizes the codebase around features rather than technical layers.
It plays well with the Event Modeling which we used to design our application and also with th Axon Framework architecture which is designed around messages.

NOTE: Thanks to new features in Axon Framework 5, like the concept of the Dynamic Consistency Boundary, the framework allows you to keep your slices totally independent of each other.
Before you always needed to share the Aggregate between them, but it's not needed anymore!

The architecture screams the capabilities of the system by making explicit:

* Commands (`createcourse` , `subscribestudent`), which are the actions that can be executed
* Events that capture what happened and may notify other parts of the system or the user
* Queries that provide information about the state of the system

The project structure includes:

[source]
----
📦 io.axoniq.demo.university
 ┣ 📂 faculty (bounded context)
 ┃ ┣ 📂 events (events shared across slices)
 ┃ ┣ 📂 write (command handling slices)
 ┃ ┃ ┣ 📂 createcourse
 ┃ ┃ ┣ 📂 changecoursecapacity
 ┃ ┃ ┣ 📂 subscribestudent
 ┃ ┃ ┗ 📂 ...
 ┃ ┣ 📂 read (query slices - FUTURE MILESTONES)
 ┃ ┗ 📂 automation (automation slices - FUTURE MILESTONES)
 ┣ 📂 shared (common code, like identifiers, exceptions, etc)
 ┗ 📂 ...
----

Each slice contains the full implementation of a feature, from command definition to command handling and event publication.
This approach allows different slices to be implemented independently and in parallel.
You may even use different implementation styles / architectures inside certain slices.
You will also see that in this tutorial.

Once that we have our project created with basic packages structure, in the next step, we may move to the framework configuration.

== Axon Configuration

Axon Framework 5 has a new configuration model that allows you to configure your framework application in a more flexible way.
We will be uncovering this new configuration model in the next steps of this tutorial.
For now, we just need basic configuration to get started.
We're going to use full potential of Event-Sourced application, so let's create a `UniversityAxonApplication` class and use `EventSourcing.configurer()`.
This will setup by default all necessary components to run an Event-Sourced application.
Components like: `EventStore`, `CommandBus`, `EventSink` etc.

[source,java]
./src/main/java/io/axoniq/demo/university/UniversityAxonApplication.java
----
public class UniversityAxonApplication {

    public static ApplicationConfigurer<?> configurer() {
        return EventSourcingConfigurer.create();
    }

}
----

Now, we are ready to start implementing the first functionality for our University application.
