:navtitle: Sample Domain & Event Modeling
:reftext: Sample Domain & Event Modeling

== The sample domain (University - Faculty)

In this sample, we are dealing with the University Domain.
The initial examples will be around the Faculty Bounded Context.

In the context there are students and courses, that students can subscribe to.
A student can enroll in the faculty.
The faculty can decide to create a course with assigned capacity—the number of students who can subscribe to a course.
The capacity of the course must be maintained.
After the course has been created, its capacity can be changed.
A student can subscribe to a course and unsubscribe.

== Event Modeling

TODO: Miro board Screen!!!

After an Event Modeling (which you can see above) session we have identified following events:

* `StudentEnrolledFaculty` - a fact that a student has enrolled faculty
* `CourseCreated` - a fact that a course has been created with assigned capacity
* `CourseCapacityChanged` - a fact that the capacity of the course has changed
* `StudentSubscribed` - a fact that the student has subscribed to the course
* `StudentUnsubscribed` - a fact that the student has unsubscribed from the course

We will model only commands for Subscribing to/Unsubscribing from a course for the sample's simplicity.

