= Commands

The first type of "Messages" that an Axon application is associated with are _*Command Messages (or simply Commands).*_ This section of the reference guide intends to cover in detail the capabilities that the Axon Framework provides to help facilitate Command Message Development.

A summary of the various sub-sections is given below.

[cols="<,<"]
|===
|Sub-Section |Purpose 

|xref:modeling/aggregate.adoc[Modeling] |Axon Framework provided components to address Aggregate Modeling concerns
|xref:command-dispatchers.adoc[Command Dispatchers]/ xref:command-handlers.adoc[Command Handlers] |Functional Development concerns for Command Messages using the Axon Framework
|xref:infrastructure.adoc[Infrastructure] |Non-Functional Development concerns for Command Messages using the Axon Framework
|xref:configuration.adoc[Configuration] |Configuration concerns for Command Messages using the Axon Framework
|===

This guide is complemented by a video tutorial which gives a practical demonstration of the concepts explained in this section. The tutorial is available at -&gt; https://www.youtube.com/watch?v=7oy4w5THFEU&feature=youtu.be[Axon Coding Tutorial - Command Messages]