= Commands
:page-aliases: README.adoc

The first type of Message that an Axon application is associated with is the Command Message, or simply Commands.
These are messages with the intent to change the state of the application in one way or another.

This section of the reference guide covers in detail the capabilities that Axon Framework provides for Command messages. A summary of the various sections is given below.

[cols="<,<"]
|===
|Sub-Section |Purpose 

|xref:modeling/aggregate.adoc[Modeling] |Axon Framework provided components to address Aggregate Modeling concerns
|xref:command-dispatchers.adoc[Command Dispatchers]/ xref:command-handlers.adoc[Command Handlers] |Functional Development concerns for Command Messages using the Axon Framework
|xref:infrastructure.adoc[Infrastructure] |Non-Functional Development concerns for Command Messages using the Axon Framework
|xref:configuration.adoc[Configuration] |Configuration concerns for Command Messages using the Axon Framework
|===

This guide is complemented by a video tutorial which gives a practical demonstration of the concepts explained in this section. The tutorial is available at -&gt; https://www.youtube.com/watch?v=7oy4w5THFEU&feature=youtu.be[Axon Coding Tutorial - Command Messages]