= Aggregate Configuration Migration
:navtitle: Configuration Migration

When migrating from Axon Framework 4 to Axon Framework 5, the configuration of aggregates has undergone significant changes to align with the new entity-based modeling approach. The following sections outline the key changes required to update your aggregate configurations.

== `EventSourcedEntityModule` instead of `AggregateConfigurer`

The configuration of entities now uses the `EventSourcedEntityModule` instead of `AggregateConfigurer`. This aligns with the new modular configuration architecture of Axon Framework 5.

[source,java]
----
// Axon Framework 5
public void configure(EventSourcingConfigurer configurer) {
    configurer.modelling().registerEventSourcedEntity(
        EventSourcedEntityModule.autodetected(String.class, GiftCard.class)
    );
}
----

== Spring Boot

If you have been using Spring Boot with Axon Framework 4, you will need to adjust your aggregate annotations and configuration to comply with the new standards in Axon Framework 5. The automatic detection and configuration of aggregates remains as before.

Most significant, the `@Aggregate` annotation is replaced by `@EventSourced`.

[#event-sourced-instead-of-aggregate-spring]
=== `@EventSourced` instead of `@Aggregate` (Spring)

[source,java]
----
// Axon Framework 4
@Aggregate
public class GiftCard {
    // ...
}

// Axon Framework 5
@EventSourced
public class GiftCard {
    // ...
}
----

Also, `@AggregateMember` is replaced by `@EntityMember` for child entities within an aggregate, see the xref:migration:paths/aggregates/multi-entity-migration.adoc[multi-entity migration] section for more details.

[IMPORTANT]
.
The `@EventSourced` annotation in Axon Framework 5/Spring Boot is the configuration replacement for `@Aggregate`, but not a fully functional/feature replacement, as attributes you may have used in AF4 (like caching, snapshotting, ...) are no longer supported. xref:migration:paths/index.adoc#missing-a-migration-path[Contact us] if you require these use-cases.
