= Queries
:page-aliases: README.adoc,query-processing.adoc

The third type of message that an Axon application is associated with is the query message, or simply queries.
These are messages that request information in a certain format. Any application can declare it's able to handle a query message and provide a response to it.

Query handling is fully async-native, with all query dispatching operations returning `CompletableFuture` or `Publisher` types. Query handlers can return these types directly, allowing for efficient asynchronous processing. Queries are routed based on the query's `MessageType` (qualified name and version), independent of the Java class used to represent the query payload.

== Types of queries

There are multiple types of queries that can be distinguished:

. xref:axon-framework-reference:queries:query-dispatchers.adoc#point-to-point-queries[Point-to-point queries]:
These are routed to a single handler, which is expected to return a single result. This is the most common type of query.
. xref:axon-framework-reference:queries:query-dispatchers.adoc#subscription-queries[Subscription queries]: These request an initial result and then continue to receive updates as long as the subscription is active. The initial result and updates are combined in a single `Publisher` stream.
. xref:axon-framework-reference:queries:query-dispatchers.adoc#streaming-queries[Streaming queries]: These queries are used to request a stream of results as a `Publisher`, which are returned as they become available. This is ideal for large result sets.

You can find more about each type of query in the xref:axon-framework-reference:queries:query-dispatchers.adoc[Query dispatchers] section.


== Subsections
A summary of the various sections is given below.

[cols="<,<"]
|===
|Subsection |Purpose

|xref:query-dispatchers.adoc[Query Dispatchers] / xref:query-handlers.adoc[Query Handlers] |Functional Development concerns for Query Messages using the Axon Framework
|xref:implementations.adoc[Implementations] |Non-Functional Development concerns for Query Messages using the Axon Framework
|xref:configuration.adoc[Configuration] |Configuration concerns for Query Messages using the Axon Framework
|===

This guide is complemented by a video tutorial which gives a practical demonstration of the concepts explained in this section. The tutorial is available at -&gt; link:https://www.youtube.com/watch?v=jS1vfc5EohM&feature=youtu.be[Axon Coding Tutorial - Query Messages]