= Command Messages
:page-needs-improvement: considerations, usage, ref
:page-needs-considerations: Design considerations needs details about command messages characteristics
:page-needs-usage: Usage section need detailed examples
:page-needs-ref: Reference section need more links to samples, source code, etc.



This document provides information about the design, implementation, and intended usage of command messages in Axon Framework.

== Design considerations

Commands are specific type of messages, used to express and an intent. To distinguish them from other message types, the framework must provide a dedicates objects.

In addition to the generic messages, command messages have the following characteristics:

=== Name



== Implementation

In Axon Framework, a command message is an immutable, serializable Java object implementing the `CommandMessage` interface.


[plantuml, svg, title="Command messaging class diagram"]
....
include::attachment$generic_messaging_classes.puml[]
include::attachment$command_messaging_classes.puml[]
....

When the communication is bidirectional, the command response is an object that implements `CommandResultMessage`.


== Usage


include::partial$command_message.adoc[tag=constructor]


include::partial$command_message.adoc[tag=static]


== Reference


.Javadoc
[%collapsible]
====
* &nbsp;
====

.Source code
[%collapsible]
====
* &nbsp;
====
