= Messages

This document provides information about the design, implementation, and intended usage of generic messaging in Axon Framework.

== Requirements

To allow components to communicate via messages, developers must represent those as Java objects. Axon Framework should provide means to construct such objects so it can use them to carry data from one component to another consistently across modules and deployment units. Below are the characteristics that every message has.

=== Uniquely identifiable

All messages are uniquely identifiable. #TODO: more info about identity#

=== Serializable

#TODO: more info about serialization#

=== Immutable

All messages are immutable. Updating a message mandates creating a new message based on the previous one, with extra information added. Immutability guarantees that messages are safe to use in a multi-threaded and distributed environment.


== Implementation

In Axon Framework, a message is an immutable, serializable Java object implementing the `Message` interface.

[plantuml, svg, title="Generic messaging class diagram"]
....
include::attachment$generic_messaging_classes.puml[]
....

When the communication is bidirectional, the response is an object that implements `ResultMessage`. A `MessageDecorator` abstract object allows for building more complex messages by wrapping existing message types.

== Usage

NOTE: Avoid using generic messages directly. Use higher-level abstractions such as xref:messages/command_messages.adoc[], xref:messages/query_messages.adoc[], or xref:messages/event_messages.adoc[] instead.

Application developers don't need to work directly with generic messages. The framework provides convenient higher-level abstractions for specific message types. It can also automatically construct the respective messages from domain-level objects, extract the payload of messages, and convert it to such domain-level objects.

That said, understanding the generic messaging design and object structure can significantly help during debugging or building custom extensions.


== Reference

.Javadoc
[%collapsible]
====
* https://apidocs.axoniq.io/latest/org/axonframework/messaging/Message.html[`Message`]
====

.Source code
[%collapsible]
====
* https://github.com/AxonFramework/AxonFramework/blob/master/messaging/src/main/java/org/axonframework/messaging/Message.java[`Message`]
====
