/*
 * Copyright (c) 2010-2026. Axon Framework
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.axonframework.messaging.core.sequencing;

import jakarta.annotation.Nonnull;
import org.axonframework.messaging.core.Message;
import org.axonframework.messaging.core.unitofwork.ProcessingContext;

import java.util.Optional;

/**
 * Interface to a policy definition for concurrent message processing.
 * <p/>
 * Some implementations are provided by default: <ul>
 * <li>{@link SequentialPolicy}: Requires that all messages are handled in the order they arrive. For event handling
 * this also means that at most 1 thread is processing messages for this processor at any time.</li>
 * <li>{@link FullConcurrencyPolicy}: Allows each message to be handled independently of any other message. Message
 * processing will typically start in the same order the messages were scheduled in, although no guarantees can be given
 * about the actual processing order.</li>
 * <li>{@link SequentialPerAggregatePolicy}: Default event processing policy. Will force events (only supports event
 * handling tasks) generated by the same aggregate to be handled sequentially. At most one thread will be processing
 * events of a single aggregate at any time.</li>
 * <li>{@link RoutingKeySequencingPolicy}: Default command processing policy. Will force commands (only supports
 * command handling tasks) routed for the same routing key to be handled sequentially.</li>
 * <li>{@link ExtractionSequencingPolicy}: Message processing policy that allows to extract the sequence identifier
 * from the message payload.</li>
 * <li>{@link MetadataSequencingPolicy}: Message processing policy that allows to extract the sequence identifier from
 * the message metadata.</li>
 * <li>{@link PropertySequencingPolicy}: Message processing policy that extracts the sequence identifier from the
 * message payload based on a given property</li>
 * <li>{@link FallbackSequencingPolicy}: Message processing policy that allows two policies in an exception-based
 * fallback behavior for sequence identifier exctraction.</li>
 * <li>{@link HierarchicalSequencingPolicy}: Message processing policy that allows to combine two policies in a
 * fallback pattern (similar to {@code FallbackSequencingPolicy}, but not exception based).</li>
 * </ul>
 *
 * @author Allard Buijze
 * @since 0.3
 */
@FunctionalInterface
public interface SequencingPolicy {

    /**
     * Returns the sequence identifier for the given {@code message}. When two messages have the same identifier (as
     * defined by their equals method), they will be executed sequentially. A {@code Optional#empty()} value indicates
     * that there are no sequencing requirements for the handling of this message.
     * <p>
     * The {@code Optional#empty()} should <b>only</b> be returned when the policy cannot determine a sequence identifier for
     * the given message. This typically happens when the policy is not applicable for the specific message type. When
     * {@code Optional#empty()} is returned, it is up to the component using this policy to provide a default behavior,
     * use another policy, throw an exception or react in any other way - as appropriate.
     *
     * @param message the message for which to get the sequencing identifier.
     * @param context the processing context in which the message is being handled. There might be limitations to the
     *                instance of the {@link ProcessingContext} depending on where the {@code SequencingPolicy} is being
     *                applied. When handling Events for exapmple, the {@link ProcessingContext} doesn't allow you to
     *                register phases actions by for example {@link ProcessingContext#on} or retrieving components by
     *                {@link ProcessingContext#component}.
     * @return a sequence identifier for the given message, or {@code Optional#empty()} if this policy cannot determine
     * a sequence identifier for the given message.
     */
    Optional<Object> getSequenceIdentifierFor(@Nonnull Message message, @Nonnull ProcessingContext context);
}
