= Axon Framework reference documentation

Welcome to the Axon Framework's reference documentation. It provides information about the modules and components of the framework, their purpose, and their intended use.

== Prerequisite knowledge

The purpose of Axon Framework is to help software developers build solutions according to specific software development concepts. While not strictly required, knowing those concepts makes it much easier to understand the framework's principles and the architectural decisions behind it. If you are new to DDD, CQRS, or Event Sourcing, we recommend reading the "xref:concepts::index.adoc[Software Development Concepts]" first.

Axon Framework alone significantly simplifies the software development process of JVM-based applications following the above principles. However, it adds even more value when used in combination with other products of the Axon family. To understand the bigger picture, please refer to "xref:understanding-axon::index.adoc[Understanding Axon]" where we explain how individual products complement each other.

== Reference documentation structure

The reference documentation aims to document the specifics of the framework's functionality, objects, interfaces, etc. It is meant to be a quick-access reference answering questions like "what is X?", "what is X used for?", "how is X implemented?", etc. Thus it follows closely the structure of Axon Framework's source code. Such approach makes it easier to quickly navigate to any specific element.

The reference documentation is valuable source during the development process. However it does not explain the underlying software design principles, deployment architectures, etc. For those please refer to the relevant xref:home::explanations.adoc[]. For step-by-step instructions and examples of how to build Axon-based applications, use the xref:home::tutorials.adoc[]. For solving known challenges and completing common tasks, there are xref:home::howtos.adoc[].

== License

Axon Framework is open source and provided under the http://www.apache.org/licenses/LICENSE-2.0[Apache License v2.0].

