= High-Level Overview

The purpose of Axon Framework is to help software developers design and build solutions according to well-established principles and best practices. To understand the framework, one first needs to understand what solutions made with it look like.

== Typical solution

Here is a somewhat simplified structure of a typical Axon-based application.

[graphviz#axon-arch-diagram, title="high-level application architecture"]
....
include::attachment$axonframework_overview.gv[]
....

TIP: If you want to build _(or merely explore)_ a simple example of such an application, the xref:giftcard::index.adoc[] tutorial walks you through the process.


=== The benefits

Note the following aspects in the <<axon-arch-diagram>> above:

 - Distinct parts communicate with each other via messages. Thus the communication pattern is the same regardless of whether components reside in the same deployment unit or multiple distributed ones.
 - There is clear separation between the command and the query sides (models) as described by xref:concepts::cqrs.adoc[CQRS]. Each side can scale and evolve independently.
 - Since the command model is independent, developers and domain experts can establish a ubiquitous language and design it following the xref:concepts::ddd.adoc[Domain-Driven Design] principles.
 - As the repository of the command model is independent, and all state changes result in events, the solution can benefit from xref:concepts::es.adoc[Event Sourcing] and store all changes instead of limiting itself to the latest state.

Constructing applications in such a way makes it possible to

 - follow closely and adequately map the actual domain
 - discuss with domain experts and reason about the impact of any change
 - postpone deployment decisions until all relevant knowledge is available
 - scale out individual components as needed

=== The Axon Framework's role

Building such a solution from scratch is a challenging and time-consuming task. Designing and implementing the infrastructure, communication, common abstractions, etc., introduces significant overhead.

Axon Framework removes that overhead by providing pre-ready components that take care of the `messaging`, `modeling`, and `event sourcing` parts.


== Structure

Axon Framework consists of several modules packaged and distributed as JAR files. This approach allows developers to pick and choose the functionality they need.

=== Bootstrap modules

Those are the modules that allow bootstrapping and configuring an Axon-based application. The application should include the preferred option as a dependency.

xref:#[Configuration]::
This module contains all the necessary components to configure an Axon-based application manually. It doesn't depend on any third party frameworks.

xref:#[Spring Boot Starter]::
This module provides Spring Boot auto-configuration for the application. It depends on Spring Framework to automatically configure all Axon Framework components.


=== Core modules

The core modules provide the essential components and building blocks for any Axon-based application.

xref:messaging:index.adoc[Messaging]::
This module provides the elements needed to build proper messaging. That includes message busses and gateways, message lifecycle and scopes, correlation, serialization and deserialization, error handling, retries, etc.

xref:modeling:index.adoc[Modeling]::
This module contains the components needed to build proper domain models on the command side. Most notably, it supports modeling essential Command-Handling Component types such as Aggregates and Sagas.

xref:eventsourcing:index.adoc[Event Sourcing]::
This module contains the components needed to provide an Event Sourcing implementation of the Command model repository.

NOTE: A typical Axon-based application almost always depends on all core modules. However, there is usually no need to declare them as dependencies explicitly. The preferred bootstrap module provides them as transitive ones.



=== Optional modules

xref:#[Spring]::
This module allows developers to configure Axon Framework components in a Spring Application context. It also provides several implementations specific to Spring Framework, such as an adapter for publishing and retrieving Axon Events on a Spring Messaging Channel.

xref:#[Axon Server Connector]::
This module provides infrastructure components that connect to Axon Server.

xref:#[Test]::
This module contains test fixtures that developers can use to test Axon-based components, such as Command Handlers, Aggregates, and Sagas. Typically one doesn't need this module at runtime and only adds it to the classpath for running tests.

xref:#[Disruptor]::
This module contains a specific CommandBus and Command Handling solution based on the Disruptor paradigm.

xref:#[Metrics]::
This module provides basic implementations based on Coda Hale to collect the monitoring information.

xref:#[Micrometer]::
This module provides basic implementations based on Micrometer to collect the monitoring information. It's a dimensional-first metrics collection facade aiming to allow developers to time, count, and gauge their code with a vendor-neutral API.

xref:#[Legacy]::
This module contains components that enable the migration of older Axon projects to use the latest Axon version.

xref:#[Tracing OpenTelemetry]::
This module contains the components needed to enable tracing with OpenTelemetry.