:navtitle: Kotlin Extension
= Kotlin

link:https://kotlinlang.org/[Kotlin,window=_blank,role=external] is a programming language which interoperates fully with Java and the JVM. As Axon is written in Java it can be used in conjunction with Kotlin too, offering a different feel when using the framework.

Some of Axon's API's work perfectly well in Java, but have a rather awkward feel when transitioning over to Kotlin. The goal of the link:https://github.com/AxonFramework/extension-kotlin[Kotlin Extension,window=_blank,role=external] is to remove that awkwardness, by providing link:https://kotlinlang.org/docs/reference/inline-functions.html[inline and reified,window=_blank,role=external] methods of Axon's API.

Several solutions are currently given, which can roughly be segregated into the distinct types of messages used by Axon. This thus provides a xref:commands.adoc[], xref:events.adoc[] and xref:queries.adoc[] section on this guide.

[NOTE]
.Experimental Release
====
Currently, the link:https://github.com/AxonFramework/extension-kotlin[Kotlin Extension,window=_blank,role=external] has been release experimentally (for example, release 0.1.0). This means that all implementations are subject to change until a full release (for example, a release 1.0.0) has been made.
====
