name: Axon Framework (Add to project)

on:
  pull_request:
    types:
      - labeled

jobs:
  add-to-project:
    name: Add PR to project
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: actions/add-to-project@v2
        with:
          project-url: https://github.com/orgs/Axoniq/projects/25
          github-token: ${{ secrets.ADD_PROJECT_TOKEN }}
          labeled: 'Type: Dependency Upgrade'
        # prevent failure if the PR is already added to the project
        continue-on-error: true
